apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-lk-server
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: lk-server
  # Minimum and maximum number of replicas.
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      # Watch the CPU consumption and if it's utilize the given percentage of
      # the maximum than it will scale the number of pods.
      name: cpu
      target:
        type: Utilization
        # 350% of the maximum CPU
        # requested 500m CPU core
        # 350% is 1750m CPU core
        averageUtilization: 350 