
# Livekit server
apiVersion: v1
kind: ConfigMap
metadata:
  name: lk-server
data:
  config.yaml: |
    keys:
      access_token: secret
    log_level: debug
    port: 7880
    redis:
      address: redis.default.svc:6379
    rtc:
      port_range_end: 60000
      port_range_start: 50000
      tcp_port: 7801
      stun_servers:
        - lk-stunner-svc.kubes.meetmo.io:443
      turn_servers:
      - credential: pass-1
        host: lk-stunner-svc.kubes.meetmo.io
        port: 443
        protocol: tls
        username: user-1
      use_external_ip: false
    turn:
      enabled: false
      loadBalancerAnnotations: {}
---
apiVersion: v1
kind: Service
metadata:
  name: lk-server
  labels:
    app.kubernetes.io/name: lk-server
    app.kubernetes.io/instance: livekit
    app.kubernetes.io/version: "v1.1.2"
spec:
  type: LoadBalancer
  ports:
    - port: 443
      targetPort: 7880
      protocol: TCP
      name: http
    - port: 7801
      targetPort: 7801
      protocol: TCP
      name: rtc-tcp
  selector:
    app.kubernetes.io/name: lk-server
    app.kubernetes.io/instance: livekit
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lk-server
  labels:
    app.kubernetes.io/name: lk-server
    app.kubernetes.io/instance: livekit
    app.kubernetes.io/version: "v1.1.2"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: lk-server
      app.kubernetes.io/instance: livekit
  template:
    metadata:
      annotations:
        linkerd.io/inject: disabled
        sidecar.istio.io/inject: "false"
      labels:
        app.kubernetes.io/name: lk-server
        app.kubernetes.io/instance: livekit
    spec:
      serviceAccountName: default
      terminationGracePeriodSeconds: 18000 # 5 hours
      containers:
        - name: lk-server
          image: "livekit/livekit-server:v1.1.2"
          imagePullPolicy: IfNotPresent
          env:
            - name: LIVEKIT_CONFIG
              valueFrom:
                configMapKeyRef:
                  name: lk-server
                  key: config.yaml
          ports:
            - name: http
              containerPort: 7880
              protocol: TCP
            - name: rtc-tcp
              containerPort: 7801
              protocol: TCP
          resources:
            limits:
              cpu: 2000m
              memory: 512Mi
            requests:
              cpu: 500m
              memory: 128Mi