apiVersion: v1
kind: ConfigMap
metadata:
  name: prosody-common
  labels:
    app.kubernetes.io/name: jitsi-meet
    app.kubernetes.io/instance: jitsi
data:
  ENABLE_AUTH: "1"
  JWT_APP_ID: "meetmo"
  ENABLE_GUESTS: "1"
  AUTH_TYPE: "jwt"
# Application secret known only to your token generator
  JWT_APP_SECRET: "A12988E22EA99EA22B97BD634FDE31CC5A3C48D96B544329B7AD3C84E7A06398"
  RESOLUTION: '720'
  RESOLUTION_MIN: '360'
  RESOLUTION_WIDTH: '1280'
  RESOLUTION_WIDTH_MIN: '640'
  START_BITRATE: '5000000'
  
  # This is just for testing purpose to enforce JVB/STUNner usage.
  # In production is recommended to turn this on.
  ENABLE_P2P: "0"
  # This shall be the domain what is pointing to your Ingress Gateway.
  PUBLIC_URL: "https://media0.cluster.meetmo.io" # TODO: Change this
  # Enable TURN
  TURN_ENABLE: "true"
  # This shall be the domain what is pointing to your STUNner Gateway.
  TURNS_HOST: "relay0.cluster.meetmo.io" # TODO: Change this
  # Define the TURN port
  TURNS_PORT: "443"
  # This shall be the same secret what is configured in STUNner gateway.
  TURN_CREDENTIALS: "6uQ3AzSCmizkf5SxvKNkyAjZYGIXs"
  JICOFO_AUTH_USER: "focus"
  JVB_AUTH_USER: "jvb"
  # These are for internal communication. Change the domains for the one what
  # is pointing to your Ingress Gateway.
  XMPP_DOMAIN: media0.cluster.meetmo.io
  XMPP_MUC_DOMAIN: muc.media0.cluster.meetmo.io
  XMPP_AUTH_DOMAIN: auth.media0.cluster.meetmo.io
  XMPP_GUEST_DOMAIN: guest.media0.cluster.meetmo.io
  XMPP_RECORDER_DOMAIN: recorder.media0.cluster.meetmo.io
  XMPP_INTERNAL_MUC_DOMAIN: internal-muc.media0.cluster.meetmo.io
  COLIBRI_REST_ENABLED: '1'
  ENABLE_XMPP_WEBSOCKET: '1'
  ENABLE_COLIBRI_WEBSOCKET: '1'
  XMPP_MUC_MODULES: "external_modules"
  TZ: 'UTC'
  LOG_LEVEL: 'info'
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: jitsi-meet
  labels:
    app.kubernetes.io/name: jitsi-meet
    app.kubernetes.io/instance: jitsi
    app.kubernetes.io/component: web
data:
  DISABLE_HTTPS: "1"
  JICOFO_AUTH_USER: 'focus'
  # If you put your Jitsi deployment in a different namespace than the default,
  # then change that part.
  XMPP_BOSH_URL_BASE: 'http://jitsi-prosody.default.svc.cluster.local:5280'
  # Whit the command below you can retrieve your cluster's public IP address
  # kubectl get svc kube-dns -n kube-system -o jsonpath='{.spec.clusterIP}'
  # Change this accordingly
  NGINX_RESOLVER: '10.245.0.10' # TODO: Change this
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: jitsi-meet-config
  labels:
    app.kubernetes.io/name: jitsi-meet-config
    app.kubernetes.io/instance: jitsi
    app.kubernetes.io/component: web
data:
  # Here you can configure your web service.
  # custom-config.js: |
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: jitsi-jvb
  labels:
    app.kubernetes.io/name: jitsi-meet
    app.kubernetes.io/instance: jitsi
    app.kubernetes.io/component: jvb
data:
  JVB_BREWERY_MUC: 'jvbbrewery'
  JVB_PORT: '30300'
  RESOLUTION: '720'
  RESOLUTION_MIN: '360'
  RESOLUTION_WIDTH: '1280'
  RESOLUTION_WIDTH_MIN: '640'
  START_BITRATE: '5000000'
  
  # This the official jitsi STUN server. You can use anything else.
  JVB_STUN_SERVERS: 'stun.l.google.com:19302,stun1.l.google.com:19302,stun2.l.google.com:19302'
  JVB_TCP_HARVESTER_DISABLED: '1'
  # Change default if your prosody deployment is in another namespace than default
  XMPP_SERVER: 'jitsi-prosody.default.svc.cluster.local'
  COLIBRI_REST_ENABLED: '0'
  ENABLE_XMPP_WEBSOCKET: '0'
  ENABLE_COLIBRI_WEBSOCKET: '0'
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: jitsi-jicofo
  labels:
    app.kubernetes.io/name: jitsi-meet
    app.kubernetes.io/instance: jitsi
    app.kubernetes.io/component: jicofo
data:
  JVB_BREWERY_MUC: 'jvbbrewery'
  # Change default if your prosody deployment is in another namespace than default
  XMPP_SERVER: 'jitsi-prosody.default.svc.cluster.local'
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: jitsi-prosody
  labels:
    app.kubernetes.io/name: prosody
    app.kubernetes.io/instance: jitsi
data:
