apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-jitsi-jvb
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: jitsi-jvb
  # Minimum and maximum number of replicas.
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      # Watch the CPU consumption and if it's utilize the given percentage of
      # the maximum than it will scale the number of pods.
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60 # 60% of the maximum CPU