apiVersion: v1
kind: Secret
metadata:
  name: prosody-jvb
  labels:
    app.kubernetes.io/name: jitsi-meet
    app.kubernetes.io/instance: jitsi
    app.kubernetes.io/component: jvb
type: Opaque
data:
  JVB_AUTH_USER: 'anZi'
  JVB_AUTH_PASSWORD: 'WEtyd0VxR1ZDeg=='
---
apiVersion: v1
kind: Secret
metadata:
  name: prosody-jicofo
  labels:
    app.kubernetes.io/name: jitsi-meet
    app.kubernetes.io/instance: jitsi
    app.kubernetes.io/component: jicofo
type: Opaque
data:
  JICOFO_AUTH_USER: 'Zm9jdXM='
  JICOFO_AUTH_PASSWORD: 'aGFjbU1ZSUcyaA=='
  JICOFO_COMPONENT_SECRET: 'VHZ1elB2SkNNeQ=='
---
apiVersion: v1
kind: Secret
metadata:
  name: jitsi-prosody
  labels:
    app.kubernetes.io/name: prosody
    app.kubernetes.io/instance: jitsi
type: Opaque
data:
